{"name": "test_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "def test_failure():\n        \"\"\"this test fails\"\"\"\n>       assert False\nE       assert False\n\ntest_alluredemo.py:10: AssertionError"}, "description": "this test fails", "start": 1609924137360, "stop": 1609924137360, "uuid": "45682007-a608-4e55-aeaf-e3987ab6f211", "historyId": "e3535563f27e644c4a3371e45c952575", "testCaseId": "cdaed0cfb7279459338013af0d443b47", "fullName": "test_alluredemo#test_failure", "labels": [{"name": "suite", "value": "test_alluredemo"}, {"name": "host", "value": "SKY-20180315FWD"}, {"name": "thread", "value": "45220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_alluredemo"}]}